Feature/project setup
Cyrus-Kiprop/weather_app pull request #2
Opened 2020-07-17 09:23 UTC by Cyrus-Kiprop

This is a weather app built using vanilla javascript, HTML, and CSS.  The user can search and request weather data for cities. Weather data consist of wind, humidity, temperature, and general feel of the day.
Requirements
1. User can toggle between Fahrenheit and Celsius units
2. Asynchronous fetching of data using promises/async and await

2020-07-17 21:08 UTC, shloch requested changes
![weather](https://user-images.githubusercontent.com/40712459/87830617-5ae86880-c879-11ea-8618-1949409dfbf0.gif)

Great job.............. well built

Please separate DOM from LOGIC, that's all you need to do

2020-07-17 21:08 UTC, shloch commented on src/components/fetchData.js
> +export default fetchDetails;
this is like the core of of your app, you need to separate LOGIC from DOM
That's all you need to do [ see [requirements](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/dom_logic_separation_requirement.png) ]

2020-07-19 15:24 UTC, shshamim63 approved these changes
## :100: Approved :+1: 
___
Hi @Cyrus-Kiprop :wave: 
Personally I loved the view of your page. And the background picture looks amazing :sunglasses: .Just found some commented codes. Your project should not contain any commented code. After removing them you are good to advance. This :+1: is from me.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-07-19 15:24 UTC, shshamim63 commented on src/components/container.js
> +// utils.appendBulkchild(container, [weatherAppWrapper]);
Please remove the commented code.

2020-07-19 15:24 UTC, shshamim63 commented on src/components/stats/cityForm.js
> +  // btn.appendChild(document.createTextNode('Submit'));
Please remove it too.

2020-07-19 16:11 UTC, merged